export const USER_VIEW_REQUEST = 'USER_VIEW_REQUEST';
export const USER_VIEW_SUCCESS = 'USER_VIEW_SUCCESS';
export const USER_VIEW_FAILURE = 'USER_VIEW_FAILURE';
export const USER_VIEW_CLEAR = 'USER_VIEW_CLEAR';
