export const SUPPORT_TICKET_VIEW_REQUEST = "SUPPORT_TICKET_VIEW_REQUEST";
export const SUPPORT_TICKET_VIEW_SUCCESS = "SUPPORT_TICKET_VIEW_SUCCESS";
export const SUPPORT_TICKET_VIEW_FAILURE = "SUPPORT_TICKET_VIEW_FAILURE";
export const SUPPORT_TICKET_VIEW_CLEAR = "SUPPORT_TICKET_VIEW_CLEAR";

