export const SUPPORT_TICKET_CREATE_REQUEST = "SUPPORT_TICKET_CREATE_REQUEST";
export const SUPPORT_TICKET_CREATE_SUCCESS = "SUPPORT_TICKET_CREATE_SUCCESS";
export const SUPPORT_TICKET_CREATE_FAILURE = "SUPPORT_TICKET_CREATE_FAILURE";
export const SUPPORT_TICKET_CREATE_CLEAR = "SUPPORT_TICKET_CREATE_CLEAR";

