export const SUPPORT_TICKET_RESPONSE_EDIT_REQUEST = "SUPPORT_TICKET_RESPONSE_EDIT_REQUEST";
export const SUPPORT_TICKET_RESPONSE_EDIT_SUCCESS = "SUPPORT_TICKET_RESPONSE_EDIT_SUCCESS";
export const SUPPORT_TICKET_RESPONSE_EDIT_FAILURE = "SUPPORT_TICKET_RESPONSE_EDIT_FAILURE";
export const SUPPORT_TICKET_RESPONSE_EDIT_CLEAR = "SUPPORT_TICKET_RESPONSE_EDIT_CLEAR";

