export const SUPPORT_TICKET_LIST_REQUEST = "SUPPORT_TICKET_LIST_REQUEST";
export const SUPPORT_TICKET_LIST_SUCCESS = "SUPPORT_TICKET_LIST_SUCCESS";
export const SUPPORT_TICKET_LIST_FAILURE = "SUPPORT_TICKET_LIST_FAILURE";
export const SUPPORT_TICKET_LIST_CLEAR = "SUPPORT_TICKET_LIST_CLEAR";

