export const SUBSCRIPTION_PAYMENT_LIST_REQUEST = 'SUBSCRIPTION_PAYMENT_LIST_REQUEST';
export const SUBSCRIPTION_PAYMENT_LIST_SUCCESS = 'SUBSCRIPTION_PAYMENT_LIST_SUCCESS';
export const SUBSCRIPTION_PAYMENT_LIST_FAILURE = 'SUBSCRIPTION_PAYMENT_LIST_FAILURE';
export const SUBSCRIPTION_PAYMENT_LIST_CLEAR = 'SUBSCRIPTION_PAYMENT_LIST_CLEAR';
