export const SUBSCRIPTION_VIEW_REQUEST = 'SUBSCRIPTION_VIEW_REQUEST';
export const SUBSCRIPTION_VIEW_SUCCESS = 'SUBSCRIPTION_VIEW_SUCCESS';
export const SUBSCRIPTION_VIEW_FAILURE = 'SUBSCRIPTION_VIEW_FAILURE';
export const SUBSCRIPTION_VIEW_CLEAR = 'SUBSCRIPTION_VIEW_CLEAR';
