export const USER_DASHBOARD_LIST_REQUEST = "USER_DASHBOARD_LIST_REQUEST";
export const USER_DASHBOARD_LIST_SUCCESS = "USER_DASHBOARD_LIST_SUCCESS";
export const USER_DASHBOARD_LIST_FAILURE = "USER_DASHBOARD_LIST_FAILURE";
export const USER_DASHBOARD_LIST_CLEAR = "USER_DASHBOARD_LIST_CLEAR";

