export const PLAN_CREATE_REQUEST = 'PLAN_CREATE_REQUEST';
export const PLAN_CREATE_SUCCESS = 'PLAN_CREATE_SUCCESS';
export const PLAN_CREATE_FAILURE = 'PLAN_CREATE_FAILURE';
export const PLAN_CREATE_CLEAR = 'PLAN_CREATE_CLEAR';
