export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST';
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS';
export const PLAN_LIST_FAILURE = 'PLAN_LIST_FAILURE';
export const PLAN_LIST_CLEAR = 'PLAN_LIST_CLEAR';
