export const PLAN_VIEW_REQUEST = 'PLAN_VIEW_REQUEST';
export const PLAN_VIEW_SUCCESS = 'PLAN_VIEW_SUCCESS';
export const PLAN_VIEW_FAILURE = 'PLAN_VIEW_FAILURE';
export const PLAN_VIEW_CLEAR = 'PLAN_VIEW_CLEAR';
