export const PLAN_DELETE_REQUEST = 'PLAN_DELETE_REQUEST';
export const PLAN_DELETE_SUCCESS = 'PLAN_DELETE_SUCCESS';
export const PLAN_DELETE_FAILURE = 'PLAN_DELETE_FAILURE';
export const PLAN_DELETE_CLEAR = 'PLAN_DELETE_CLEAR';
