export const PLAN_EDIT_REQUEST = 'PLAN_EDIT_REQUEST';
export const PLAN_EDIT_SUCCESS = 'PLAN_EDIT_SUCCESS';
export const PLAN_EDIT_FAILURE = 'PLAN_EDIT_FAILURE';
export const PLAN_EDIT_CLEAR = 'PLAN_EDIT_CLEAR';
