export const USER_FEEDBACK_LIST_REQUEST = 'USER_FEEDBACK_LIST_REQUEST';
export const USER_FEEDBACK_LIST_SUCCESS = 'USER_FEEDBACK_LIST_SUCCESS';
export const USER_FEEDBACK_LIST_FAILURE = 'USER_FEEDBACK_LIST_FAILURE';
export const USER_FEEDBACK_LIST_CLEAR = 'USER_FEEDBACK_LIST_CLEAR';
