export const USER_FEEDBACK_VIEW_REQUEST = 'USER_FEEDBACK_VIEW_REQUEST';
export const USER_FEEDBACK_VIEW_SUCCESS = 'USER_FEEDBACK_VIEW_SUCCESS';
export const USER_FEEDBACK_VIEW_FAILURE = 'USER_FEEDBACK_VIEW_FAILURE';
export const USER_FEEDBACK_VIEW_CLEAR = 'USER_FEEDBACK_VIEW_CLEAR';
