export const USER_FEEDBACK_DELETE_REQUEST = 'USER_FEEDBACK_DELETE_REQUEST';
export const USER_FEEDBACK_DELETE_SUCCESS = 'USER_FEEDBACK_DELETE_SUCCESS';
export const USER_FEEDBACK_DELETE_FAILURE = 'USER_FEEDBACK_DELETE_FAILURE';
export const USER_FEEDBACK_DELETE_CLEAR = 'USER_FEEDBACK_DELETE_CLEAR';
