export const USER_FEEDBACK_EDIT_REQUEST = 'USER_FEEDBACK_EDIT_REQUEST';
export const  USER_FEEDBACK_EDIT_SUCCESS = 'USER_FEEDBACK_EDIT_SUCCESS';
export const  USER_FEEDBACK_EDIT_FAILURE = 'USER_FEEDBACK_EDIT_FAILURE';
export const  USER_FEEDBACK_EDIT_CLEAR = 'USER_FEEDBACK_EDIT_CLEAR';
