export const ADMIN_DASHBOARD_LIST_REQUEST = "ADMIN_DASHBOARD_LIST_REQUEST";
export const ADMIN_DASHBOARD_LIST_SUCCESS = "ADMIN_DASHBOARD_LIST_SUCCESS";
export const ADMIN_DASHBOARD_LIST_FAILURE = "ADMIN_DASHBOARD_LIST_FAILURE";
export const ADMIN_DASHBOARD_LIST_CLEAR = "ADMIN_DASHBOARD_LIST_CLEAR";

