export const SUBSCRIBER_CREATE_REQUEST = 'SUBSCRIBER_CREATE_REQUEST';
export const SUBSCRIBER_CREATE_SUCCESS = 'SUBSCRIBER_CREATE_SUCCESS';
export const SUBSCRIBER_CREATE_FAILURE = 'SUBSCRIBER_CREATE_FAILURE';
export const SUBSCRIBER_CREATE_CLEAR = 'SUBSCRIBER_CREATE_CLEAR';
